import { Roboto } from "next/font/google";
import "./globals.css";
import "@/styles/index.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";
import { ConfigProvider, App } from "antd";
import Layout from "@/components/layout/Layout";
import QueryProvider from "@/components/providers/QueryProvider";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} antialiased`}>
        <AntdRegistry>
          <QueryProvider>
            <ConfigProvider
              theme={{
                token: {
                  colorPrimary: "#2ec4b6",
                  colorSecondary: "#3a86ff",
                  colorSurface: "#ffffff",
                  colorTextSubtle: "#5e6b7a",
                  colorSuccess: "#00c896",
                  colorWarning: "#ffa800",
                  colorError: "#ff5a5f",
                },
              }}
            >
              <App>
                <Layout>{children}</Layout>
              </App>
            </ConfigProvider>
          </QueryProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
