/**
 * Fixed attributes configuration for each product category/componentType
 * Each category has predefined attributes that should be displayed in the product form
 */

export const CATEGORY_FIXED_ATTRIBUTES = {
  CPU: [
    {
      key: "socket",
      label: "Socket",
      type: "text",
      placeholder: "Ví dụ: AM4, LGA1200, LGA1700",
      required: true,
    },
    {
      key: "cores",
      label: "Số nhân",
      type: "number",
      placeholder: "Ví dụ: 8",
      required: true,
    },
    {
      key: "threads",
      label: "Số luồng",
      type: "number",
      placeholder: "Ví dụ: 16",
      required: true,
    },
    {
      key: "baseClock",
      label: "Xung nhịp cơ bản",
      type: "text",
      placeholder: "Ví dụ: 3.6 GHz",
      required: true,
    },
    {
      key: "boostClock",
      label: "Xung nhịp tối đa",
      type: "text",
      placeholder: "Ví dụ: 4.6 GHz",
      required: false,
    },
    {
      key: "cache",
      label: "Bộ nhớ đệm",
      type: "text",
      placeholder: "Ví dụ: 32MB",
      required: false,
    },
    {
      key: "tdp",
      label: "TDP / Tiêu thụ điện năng",
      type: "text",
      placeholder: "Ví dụ: 65W, 65W - 148W",
      required: false,
    },
    {
      key: "cpuBrand",
      label: "Thương hiệu CPU",
      type: "text",
      placeholder: "Ví dụ: Intel, AMD",
      required: false,
    },
    {
      key: "series",
      label: "Series",
      type: "text",
      placeholder: "Ví dụ: Core i5, Ryzen 5",
      required: false,
    },
    {
      key: "generation",
      label: "Thế hệ",
      type: "text",
      placeholder: "Ví dụ: Intel Core thế hệ thứ 14",
      required: false,
    },
    {
      key: "processingSpeed",
      label: "Tốc độ xử lý",
      type: "textarea",
      placeholder:
        "Ví dụ:\n- Tần số Turbo tối đa 4.7 GHz\n- Tốc độ Turbo tối đa của P-core 4.7 GHz",
      required: false,
    },
    {
      key: "maxTemperature",
      label: "Nhiệt độ tối đa",
      type: "text",
      placeholder: "Ví dụ: 100°C",
      required: false,
    },
    {
      key: "ramSupport",
      label: "RAM hỗ trợ",
      type: "textarea",
      placeholder: "Ví dụ:\n- Hỗ trợ tối đa: 192 GB\n- DDR5 up to 4800 MT/s",
      required: false,
    },
    {
      key: "integratedGraphics",
      label: "Đồ hoạ tích hợp",
      type: "text",
      placeholder: "Ví dụ: Intel® UHD Graphics 730",
      required: false,
    },
    {
      key: "pciePorts",
      label: "Số cổng PCI Express",
      type: "number",
      placeholder: "Ví dụ: 20",
      required: false,
    },
    {
      key: "pcieVersion",
      label: "Phiên bản PCI Express",
      type: "text",
      placeholder: "Ví dụ: PCIe® 5.0 & PCIe® 4.0",
      required: false,
    },
  ],

  VGA: [
    {
      key: "chipsetManufacturer",
      label: "Nhà sản xuất chipset",
      type: "text",
      placeholder: "Ví dụ: NVIDIA, AMD",
      required: false,
    },
    {
      key: "graphicsChipSeries",
      label: "Series chip đồ họa",
      type: "text",
      placeholder: "Ví dụ: GeForce RTX 50 series, Radeon RX 7000 series",
      required: false,
    },
    {
      key: "chipset",
      label: "VGA / Chipset",
      type: "text",
      placeholder: "Ví dụ: GeForce RTX 5060Ti, RTX 4080, RX 7800 XT",
      required: true,
    },
    {
      key: "gpuSeries",
      label: "Series",
      type: "text",
      placeholder: "Ví dụ: iGame, ROG Strix, Gaming X",
      required: false,
    },
    {
      key: "memory",
      label: "Bộ nhớ",
      type: "text",
      placeholder: "Ví dụ: 16GB GDDR7 ( 28Gbps / 128-bit ), 16GB GDDR6X",
      required: true,
    },
    {
      key: "memoryInterface",
      label: "Bus bộ nhớ",
      type: "text",
      placeholder: "Ví dụ: 256-bit, 128-bit",
      required: false,
    },
    {
      key: "gpuClock",
      label: "VGA clock",
      type: "textarea",
      placeholder: "Ví dụ:\nBase: 2407Mhz\nBoost: 2572Mhz",
      required: false,
    },
    {
      key: "coreClock",
      label: "Xung nhịp VGA",
      type: "text",
      placeholder: "Ví dụ: 2210 MHz",
      required: false,
    },
    {
      key: "memoryClock",
      label: "Xung nhịp bộ nhớ",
      type: "text",
      placeholder: "Ví dụ: 22.4 Gbps",
      required: false,
    },
    {
      key: "cudaCores",
      label: "Số lượng đơn vị xử lý",
      type: "text",
      placeholder: "Ví dụ: 4608 CUDA cores, 10240 Stream Processors",
      required: false,
    },
    {
      key: "maxResolution",
      label: "Độ phân giải tối đa",
      type: "text",
      placeholder: "Ví dụ: 7680x4320",
      required: false,
    },
    {
      key: "outputs",
      label: "Cổng kết nối",
      type: "array",
      placeholder: "Ví dụ: 1 x HDMI 2.1b, 3 x DisplayPort 2.1b",
      required: false,
    },
    {
      key: "cooling",
      label: "Tản nhiệt",
      type: "text",
      placeholder: "Ví dụ: Tản nhiệt 3 quạt, Dual Fan, AIO Liquid",
      required: false,
    },
    {
      key: "powerConnectors",
      label: "Cổng nguồn",
      type: "text",
      placeholder: "Ví dụ: 2x 8-pin",
      required: false,
    },
    {
      key: "recommendedPSU",
      label: "Nguồn đề xuất",
      type: "text",
      placeholder: "Ví dụ: 600W, 750W",
      required: false,
    },
    {
      key: "hasLED",
      label: "Có LED",
      type: "boolean",
      placeholder: "",
      required: false,
    },
    {
      key: "ledType",
      label: "Loại LED",
      type: "select",
      placeholder: "Chọn loại LED",
      options: [
        { value: "none", label: "Không có LED" },
        { value: "RGB", label: "RGB" },
        { value: "ARGB", label: "ARGB (Addressable RGB)" },
        { value: "single-color", label: "Màu đơn" },
        { value: "other", label: "Khác" },
      ],
      required: false,
      dependsOn: "hasLED",
    },
  ],

  RAM: [
    {
      key: "ramSticks",
      label: "Số thanh RAM",
      type: "number",
      placeholder: "Ví dụ: 1, 2, 4",
      required: false,
    },
    {
      key: "capacity",
      label: "Dung lượng mỗi thanh",
      type: "text",
      placeholder: "Ví dụ: 16GB, 8GB",
      required: false,
    },
    {
      key: "capacityTotal",
      label: "Dung lượng",
      type: "text",
      placeholder: "Ví dụ: 1 x 16GB, 2 x 8GB",
      required: true,
    },
    {
      key: "generation",
      label: "Thế hệ",
      type: "text",
      placeholder: "Ví dụ: DDR4, DDR5",
      required: true,
    },
    {
      key: "busSpeed",
      label: "Bus",
      type: "text",
      placeholder: "Ví dụ: 3200MHz, 5600MHz",
      required: true,
    },
    {
      key: "speed",
      label: "Tốc độ (tự động)",
      type: "text",
      placeholder: "Ví dụ: DDR4-3200, DDR5-5600",
      required: false,
    },
    {
      key: "timing",
      label: "Timing",
      type: "text",
      placeholder: "Ví dụ: 22, CL16-18-18-38",
      required: false,
    },
    {
      key: "voltage",
      label: "Voltage",
      type: "text",
      placeholder: "Ví dụ: 1.2V, 1.35V",
      required: false,
    },
    {
      key: "formFactor",
      label: "Form Factor",
      type: "text",
      placeholder: "Ví dụ: DIMM, SO-DIMM",
      required: false,
    },
    {
      key: "hasLED",
      label: "Có LED",
      type: "boolean",
      placeholder: "",
      required: false,
    },
    {
      key: "ledType",
      label: "Đèn LED",
      type: "select",
      placeholder: "Chọn loại LED",
      options: [
        { value: "none", label: "Không LED" },
        { value: "RGB", label: "RGB" },
        { value: "ARGB", label: "ARGB (Addressable RGB)" },
        { value: "single-color", label: "Màu đơn" },
        { value: "other", label: "Khác" },
      ],
      required: false,
      dependsOn: "hasLED",
    },
  ],

  Mainboard: [
    {
      key: "mbSeries",
      label: "Series mainboard",
      type: "text",
      placeholder: "Ví dụ: Gaming, Pro, Aorus",
      required: false,
    },
    {
      key: "chipsetMB",
      label: "Chipset",
      type: "text",
      placeholder: "Ví dụ: B860, Z790, X670E",
      required: true,
    },
    {
      key: "socketMB",
      label: "Socket",
      type: "text",
      placeholder: "Ví dụ: 1851, LGA1700, AM5",
      required: true,
    },
    {
      key: "formFactorMB",
      label: "Kích thước",
      type: "text",
      placeholder: "Ví dụ: ATX, Micro-ATX, Mini-ITX",
      required: true,
    },
    {
      key: "supportedCPU",
      label: "CPU hỗ trợ",
      type: "array",
      placeholder: "Ví dụ: Intel 12th Gen, Intel 13th Gen",
      required: false,
    },
    {
      key: "memorySlots",
      label: "Khe RAM tối đa",
      type: "number",
      placeholder: "Ví dụ: 4",
      required: true,
    },
    {
      key: "ramType",
      label: "Kiểu RAM hỗ trợ",
      type: "text",
      placeholder: "Ví dụ: DDR4, DDR5",
      required: true,
    },
    {
      key: "maxMemory",
      label: "Hỗ trợ bộ nhớ tối đa",
      type: "text",
      placeholder: "Ví dụ: 128GB, 256GB",
      required: false,
    },
    {
      key: "ramBusSupport",
      label: "Bus RAM hỗ trợ",
      type: "textarea",
      placeholder: "Ví dụ:\n8800(O.C), 8000(O.C), 8400(OC), 8600(OC)",
      required: false,
    },
    {
      key: "storageConnectors",
      label: "Lưu trữ",
      type: "array",
      placeholder: "Ví dụ: 3 x M.2 NVMe, 4 x SATA 3 6Gb/s",
      required: false,
    },
    {
      key: "m2Type",
      label: "Kiểu khe M.2 hỗ trợ",
      type: "text",
      placeholder: "Ví dụ: M.2 NVMe, M.2 SATA, M.2 NVMe & SATA",
      required: false,
    },
    {
      key: "videoOutputs",
      label: "Cổng xuất hình",
      type: "text",
      placeholder: "Ví dụ: 1 x HDMI, 1 x DisplayPort, 1 x Thunderbolt 4",
      required: false,
    },
    {
      key: "expansionSlots",
      label: "Khe PCI",
      type: "array",
      placeholder: "Ví dụ: 4x PCI-E x16 slot",
      required: false,
    },
    {
      key: "hasLED",
      label: "Có LED",
      type: "boolean",
      placeholder: "",
      required: false,
    },
    {
      key: "ledType",
      label: "Đèn LED",
      type: "select",
      placeholder: "Chọn loại LED",
      options: [
        { value: "none", label: "Không có LED" },
        { value: "RGB", label: "RGB" },
        { value: "ARGB", label: "ARGB (Addressable RGB)" },
        { value: "single-color", label: "Màu đơn" },
        { value: "other", label: "Khác" },
      ],
      required: false,
      dependsOn: "hasLED",
    },
    {
      key: "usbPorts",
      label: "Số cổng USB",
      type: "textarea",
      placeholder:
        "Ví dụ:\n- 1 x USB Type C ( Tối đa 2)\n- 3 x USB 3.2( Tối đa 7)",
      required: false,
    },
    {
      key: "lan",
      label: "LAN",
      type: "text",
      placeholder: "Ví dụ: 1 x LAN 5Gb/s, 2.5Gb Ethernet",
      required: false,
    },
    {
      key: "wireless",
      label: "Kết nối không dây",
      type: "text",
      placeholder: "Ví dụ: Wi-Fi 7 (802.11be), Bluetooth 5.4",
      required: false,
    },
    {
      key: "audio",
      label: "Âm thanh",
      type: "textarea",
      placeholder:
        "Ví dụ:\nRealtek® ALC897 Codec\n7.1-Channel High Definition Audio",
      required: false,
    },
  ],

  Storage: [
    {
      key: "storageType",
      label: "Kiểu ổ cứng",
      type: "select",
      placeholder: "Chọn kiểu ổ cứng",
      options: [
        { value: "SSD", label: "SSD" },
        { value: "HDD", label: "HDD" },
        { value: "NVMe SSD", label: "NVMe SSD" },
        { value: "SATA SSD", label: "SATA SSD" },
        { value: "M.2 SSD", label: "M.2 SSD" },
      ],
      required: true,
    },
    {
      key: "capacity",
      label: "Dung lượng",
      type: "text",
      placeholder: "Ví dụ: 500GB, 1TB",
      required: true,
    },
    {
      key: "interface",
      label: "Kết nối",
      type: "text",
      placeholder: "Ví dụ: M.2 NVMe, SATA III, NVMe PCIe 4.0",
      required: true,
    },
    {
      key: "nandType",
      label: "Bộ nhớ NAND",
      type: "text",
      placeholder: "Ví dụ: 3D-NAND, TLC, QLC, MLC",
      required: false,
    },
    {
      key: "formFactorStorage",
      label: "Kích thước",
      type: "text",
      placeholder: 'Ví dụ: M.2 2280, 2.5", 3.5"',
      required: true,
    },
    {
      key: "readSpeed",
      label: "Tốc độ đọc",
      type: "text",
      placeholder: "Ví dụ: 5000MB/s, 7,000 MB/s",
      required: false,
    },
    {
      key: "writeSpeed",
      label: "Tốc độ ghi",
      type: "text",
      placeholder: "Ví dụ: 3000MB/s, 6,000 MB/s",
      required: false,
    },
  ],

  PSU: [
    {
      key: "psuSeries",
      label: "Series",
      type: "text",
      placeholder: "Ví dụ: MAG, RMx, Focus",
      required: false,
    },
    {
      key: "wattage",
      label: "Công suất tối đa",
      type: "text",
      placeholder: "Ví dụ: 750W, 850W",
      required: true,
    },
    {
      key: "efficiency",
      label: "Hiệu suất",
      type: "text",
      placeholder: "Ví dụ: 80 Plus Bronze, 80 Plus Gold, 80 Plus Platinum",
      required: true,
    },
    {
      key: "modular",
      label: "Loại dây",
      type: "text",
      placeholder: "Ví dụ: Full Modular, Semi Modular, Non-Modular",
      required: false,
    },
    {
      key: "cables",
      label: "Số cổng cắm",
      type: "textarea",
      placeholder:
        "Ví dụ:\n1 x 24-pin Main\n2 x 8-pin (4+4) EPS\n1 x 16-pin PCIE",
      required: false,
    },
    {
      key: "coolingFan",
      label: "Quạt làm mát",
      type: "text",
      placeholder: "Ví dụ: 1 x 120 mm, 140mm",
      required: false,
    },
    {
      key: "inputVoltage",
      label: "Nguồn đầu vào",
      type: "text",
      placeholder: "Ví dụ: 100 - 240VAC, 115-230V",
      required: false,
    },
  ],

  Case: [
    {
      key: "caseName",
      label: "Tên của case",
      type: "text",
      placeholder: "Ví dụ: Z20, H510, O11 Dynamic",
      required: false,
    },
    {
      key: "caseType",
      label: "Loại case",
      type: "text",
      placeholder: "Ví dụ: Mini Tower, Mid Tower, Full Tower",
      required: true,
    },
    {
      key: "material",
      label: "Chất liệu",
      type: "text",
      placeholder: "Ví dụ: Thép, Nhôm, Nhựa, Thép + Nhựa",
      required: false,
    },
    {
      key: "sidePanelMaterial",
      label: "Chất liệu nắp hông",
      type: "text",
      placeholder: "Ví dụ: Kính cường lực, Nhựa, Thép",
      required: false,
    },
    {
      key: "supportedMainboard",
      label: "Hỗ trợ mainboard",
      type: "array",
      placeholder: "Ví dụ: Mini-ITX, Micro-ATX, ATX",
      required: false,
    },
    {
      key: "maxGPULength",
      label: "Chiều dài VGA tối đa",
      type: "text",
      placeholder: "Ví dụ: 380mm",
      required: false,
    },
    {
      key: "maxCPUCoolerHeight",
      label: "Hỗ trợ tản nhiệt CPU cao",
      type: "text",
      placeholder: "Ví dụ: 180mm, 165mm",
      required: false,
    },
    {
      key: "maxRadiatorSize",
      label: "Kích thước radiator tối đa",
      type: "text",
      placeholder: "Ví dụ: 240 mm, 360 mm",
      required: false,
    },
    {
      key: "driveBays",
      label: "Số lượng ổ đĩa hỗ trợ",
      type: "array",
      placeholder: 'Ví dụ: 1 x 3.5", 3 x 2.5"',
      required: false,
    },
    {
      key: "frontPorts",
      label: "Cổng kết nối",
      type: "array",
      placeholder: "Ví dụ: 1 x USB 3.2, 1 x USB Type C",
      required: false,
    },
    {
      key: "topFanSupport",
      label: "Loại quạt hỗ trợ phía trên",
      type: "text",
      placeholder: "Ví dụ: 2 x 120 mm, 2 x 140 mm",
      required: false,
    },
    {
      key: "rearFanSupport",
      label: "Loại quạt hỗ trợ phía sau",
      type: "text",
      placeholder: "Ví dụ: 1 x 120 mm, 1 x 92 mm",
      required: false,
    },
    {
      key: "bottomFanSupport",
      label: "Loại quạt hỗ trợ bên dưới",
      type: "text",
      placeholder: "Ví dụ: 2 x 120 mm, 2 x 140 mm",
      required: false,
    },
    {
      key: "pciSlots",
      label: "Số slot PCI",
      type: "number",
      placeholder: "Ví dụ: 4, 7",
      required: false,
    },
    {
      key: "hasLED",
      label: "Có LED",
      type: "boolean",
      placeholder: "",
      required: false,
    },
    {
      key: "ledType",
      label: "Đèn LED",
      type: "select",
      placeholder: "Chọn loại LED",
      options: [
        { value: "none", label: "Không có LED" },
        { value: "RGB", label: "RGB" },
        { value: "ARGB", label: "ARGB (Addressable RGB)" },
        { value: "single-color", label: "Màu đơn" },
        { value: "other", label: "Khác" },
      ],
      required: false,
      dependsOn: "hasLED",
    },
  ],

  Monitor: [
    {
      key: "screenSize",
      label: "Kích thước màn hình",
      type: "text",
      placeholder: 'Ví dụ: 27", 32"',
      required: true,
    },
    {
      key: "resolution",
      label: "Độ phân giải",
      type: "text",
      placeholder: "Ví dụ: 2560x1440, 3840x2160",
      required: true,
    },
    {
      key: "panelType",
      label: "Loại panel",
      type: "text",
      placeholder: "Ví dụ: IPS, VA, TN, OLED",
      required: true,
    },
    {
      key: "refreshRate",
      label: "Tần số quét",
      type: "text",
      placeholder: "Ví dụ: 144Hz, 165Hz",
      required: false,
    },
    {
      key: "responseTime",
      label: "Thời gian phản hồi",
      type: "text",
      placeholder: "Ví dụ: 1ms, 4ms",
      required: false,
    },
    {
      key: "brightness",
      label: "Độ sáng",
      type: "text",
      placeholder: "Ví dụ: 400 nits",
      required: false,
    },
    {
      key: "contrast",
      label: "Độ tương phản",
      type: "text",
      placeholder: "Ví dụ: 1000:1",
      required: false,
    },
    {
      key: "colorGamut",
      label: "Dải màu",
      type: "text",
      placeholder: "Ví dụ: 99% sRGB, 95% DCI-P3",
      required: false,
    },
    {
      key: "features",
      label: "Tính năng",
      type: "array",
      placeholder: "Ví dụ: HDR400, FreeSync Premium",
      required: false,
    },
  ],

  Cooling: [
    {
      key: "coolingType",
      label: "Dạng tản nhiệt",
      type: "text",
      placeholder: "Ví dụ: Tản nước AIO, Air Cooler, AIO Liquid",
      required: true,
    },
    {
      key: "fanSize",
      label: "Kích thước quạt (mm)",
      type: "text",
      placeholder: "Ví dụ: 3 x 360 mm, 120mm, 140mm",
      required: false,
    },
    {
      key: "socketCompatibility",
      label: "Socket được hỗ trợ",
      type: "array",
      placeholder: "Ví dụ: Intel LGA 1151-v2, AMD AM4, AMD AM5, Intel LGA 1700",
      required: true,
    },
    {
      key: "hasLED",
      label: "Có LED",
      type: "boolean",
      placeholder: "",
      required: false,
    },
    {
      key: "ledType",
      label: "Đèn LED",
      type: "select",
      placeholder: "Chọn loại LED",
      options: [
        { value: "none", label: "Không LED" },
        { value: "RGB", label: "RGB" },
        { value: "ARGB", label: "ARGB (Addressable RGB)" },
        { value: "single-color", label: "Màu đơn" },
        { value: "other", label: "Khác" },
      ],
      required: false,
      dependsOn: "hasLED",
    },
    {
      key: "coolingMaterial",
      label: "Chất liệu tản nhiệt",
      type: "text",
      placeholder: "Ví dụ: Nhôm, Đồng, Nhôm + Đồng",
      required: false,
    },
    {
      key: "radiatorSize",
      label: "Kích thước Radiator (cm)",
      type: "text",
      placeholder: "Ví dụ: 401 x 120 x 27 mm, 240 mm, 360 mm",
      required: false,
    },
    {
      key: "height",
      label: "Chiều cao (cm)",
      type: "text",
      placeholder: "Ví dụ: 600 mm, 165mm",
      required: false,
    },
    {
      key: "pumpRPM",
      label: "Số vòng quay của bơm (RPM)",
      type: "text",
      placeholder: "Ví dụ: 1,200 – 2,800 ± 300 RPM",
      required: false,
    },
    {
      key: "fanRPM",
      label: "Số vòng quay của quạt (RPM)",
      type: "text",
      placeholder: "Ví dụ: 500 - 2,400 ± 250 RPM",
      required: false,
    },
    {
      key: "airflowCFM",
      label: "Lưu lượng không khí (CFM)",
      type: "text",
      placeholder: "Ví dụ: 75.05 CFM",
      required: false,
    },
    {
      key: "noiseLevel",
      label: "Độ ồn (dBA)",
      type: "text",
      placeholder: "Ví dụ: 31.9 dBA, 25 dB",
      required: false,
    },
  ],

  Keyboard: [
    {
      key: "keyboardType",
      label: "Loại bàn phím",
      type: "text",
      placeholder: "Ví dụ: Mechanical, Membrane",
      required: true,
    },
    {
      key: "switchType",
      label: "Loại switch",
      type: "text",
      placeholder: "Ví dụ: Cherry MX Red, Blue",
      required: false,
    },
    {
      key: "layout",
      label: "Bố cục",
      type: "text",
      placeholder: "Ví dụ: Full-size, TKL, 60%",
      required: false,
    },
    {
      key: "connectivity",
      label: "Kết nối",
      type: "text",
      placeholder: "Ví dụ: USB, Wireless, Bluetooth",
      required: false,
    },
    {
      key: "hasLED",
      label: "Có LED",
      type: "boolean",
      placeholder: "",
      required: false,
    },
    {
      key: "ledType",
      label: "Loại LED",
      type: "select",
      placeholder: "Chọn loại LED",
      options: [
        { value: "none", label: "Không có LED" },
        { value: "RGB", label: "RGB" },
        { value: "ARGB", label: "ARGB (Addressable RGB)" },
        { value: "single-color", label: "Màu đơn" },
        { value: "other", label: "Khác" },
      ],
      required: false,
      dependsOn: "hasLED",
    },
  ],

  Mouse: [
    {
      key: "sensorType",
      label: "Loại cảm biến",
      type: "text",
      placeholder: "Ví dụ: Optical, Laser",
      required: true,
    },
    {
      key: "dpi",
      label: "DPI",
      type: "text",
      placeholder: "Ví dụ: 16000 DPI",
      required: false,
    },
    {
      key: "connectivity",
      label: "Kết nối",
      type: "text",
      placeholder: "Ví dụ: USB, Wireless, Bluetooth",
      required: false,
    },
    {
      key: "buttons",
      label: "Số nút",
      type: "number",
      placeholder: "Ví dụ: 6",
      required: false,
    },
    {
      key: "hasLED",
      label: "Có LED",
      type: "boolean",
      placeholder: "",
      required: false,
    },
    {
      key: "ledType",
      label: "Loại LED",
      type: "select",
      placeholder: "Chọn loại LED",
      options: [
        { value: "none", label: "Không có LED" },
        { value: "RGB", label: "RGB" },
        { value: "ARGB", label: "ARGB (Addressable RGB)" },
        { value: "single-color", label: "Màu đơn" },
        { value: "other", label: "Khác" },
      ],
      required: false,
      dependsOn: "hasLED",
    },
  ],

  Audio: [
    {
      key: "audioType",
      label: "Loại thiết bị",
      type: "text",
      placeholder: "Ví dụ: Headphone, Speaker, DAC",
      required: true,
    },
    {
      key: "driverSize",
      label: "Kích thước driver",
      type: "text",
      placeholder: "Ví dụ: 50mm",
      required: false,
    },
    {
      key: "frequencyResponse",
      label: "Dải tần số",
      type: "text",
      placeholder: "Ví dụ: 20Hz - 20kHz",
      required: false,
    },
    {
      key: "impedance",
      label: "Trở kháng",
      type: "text",
      placeholder: "Ví dụ: 32 Ohm",
      required: false,
    },
  ],

  Networking: [
    {
      key: "networkType",
      label: "Loại thiết bị",
      type: "text",
      placeholder: "Ví dụ: Router, Switch, Network Card",
      required: true,
    },
    {
      key: "wifiStandard",
      label: "Chuẩn Wi-Fi",
      type: "text",
      placeholder: "Ví dụ: Wi-Fi 6, Wi-Fi 6E",
      required: false,
    },
    {
      key: "ethernetPorts",
      label: "Số cổng Ethernet",
      type: "number",
      placeholder: "Ví dụ: 4",
      required: false,
    },
    {
      key: "speed",
      label: "Tốc độ",
      type: "text",
      placeholder: "Ví dụ: 1Gbps, 2.5Gbps",
      required: false,
    },
  ],

  Other: [],
};

/**
 * Common attributes that apply to all product types
 */
export const COMMON_ATTRIBUTES = [
  {
    key: "model",
    label: "Model",
    type: "text",
    placeholder: "Ví dụ: RTX 4080",
    required: false,
  },
  {
    key: "partNumber",
    label: "Part Number",
    type: "text",
    placeholder: "Ví dụ: RTX4080-16G",
    required: false,
  },
  {
    key: "warranty",
    label: "Bảo hành",
    type: "text",
    placeholder: "Ví dụ: 2 năm, 36 tháng",
    required: false,
  },
  {
    key: "productType",
    label: "Loại hàng",
    type: "select",
    placeholder: "Chọn loại hàng",
    options: [
      { value: "Hàng thông thường", label: "Hàng thông thường" },
      { value: "Hàng chính hãng", label: "Hàng chính hãng" },
      { value: "Hàng nhập khẩu", label: "Hàng nhập khẩu" },
      { value: "Hàng xách tay", label: "Hàng xách tay" },
    ],
    required: false,
  },
  {
    key: "weight",
    label: "Trọng lượng",
    type: "text",
    placeholder: "Ví dụ: 500g, 2.5kg",
    required: false,
  },
  {
    key: "dimensions",
    label: "Kích thước",
    type: "text",
    placeholder: "Ví dụ: 300 x 200 x 50 mm",
    required: false,
  },
  {
    key: "useCases",
    label: "Nhu cầu",
    type: "array",
    placeholder: "Ví dụ: Gaming, Văn phòng, Đồ họa - Kỹ thuật",
    required: false,
    options: [
      { value: "Gaming", label: "Gaming" },
      { value: "Văn phòng", label: "Văn phòng" },
      { value: "Đồ họa - Kỹ thuật", label: "Đồ họa - Kỹ thuật" },
      { value: "Doanh nghiệp", label: "Doanh nghiệp" },
      { value: "Học sinh - Sinh viên", label: "Học sinh - Sinh viên" },
      { value: "Streaming", label: "Streaming" },
      { value: "Mining", label: "Mining" },
      { value: "Server", label: "Server" },
    ],
  },
];

/**
 * Get fixed attributes for a given componentType
 * @param {string} componentType - The component type (CPU, VGA, etc.)
 * @returns {Array} Array of attribute definitions
 */
export const getFixedAttributesForCategory = (componentType) => {
  if (!componentType) return [];
  return CATEGORY_FIXED_ATTRIBUTES[componentType] || [];
};

/**
 * Get all attributes (common + fixed) for a given componentType
 * @param {string} componentType - The component type
 * @returns {Array} Array of attribute definitions
 */
export const getAllAttributesForCategory = (componentType) => {
  const fixed = getFixedAttributesForCategory(componentType);
  return [...COMMON_ATTRIBUTES, ...fixed];
};
